env:
  CIRRUS_CLONE_DEPTH: 1

task:
  persistent_worker:
    labels:
      jail: FreeBSD-14-0-release-doc
  timeout_in: 20m
  test_script:
    - git submodule init
    - git submodule update
    - hugo
